Repository poporonnet/kcmsx, pull requests merged in 2024-08, with the labels that each got.

#165 fix: tseslint v8で増えたlintのerrorの修正
  packages/config/eslint.config.js
  packages/config/src/types/derived/config.ts
  packages/kcmsf/src/pages/matchList.tsx
Labels: 改善

#153 feat: コンフィグの項目の型ガードを追加
  packages/config/README.md
  packages/config/index.ts
  packages/config/src/utility/typeGuard.test.ts
  packages/config/src/utility/typeGuard.ts
Labels: 改善

#169 feat: Entryにクラブ を追加
  packages/kcms/src/entry/entry.test.ts
  packages/kcms/src/entry/entry.ts
  packages/kcms/src/entry/service/entry.ts
Labels: 新機能, backend

#175 fix: kcmsからconfigパッケージを使用できるようにする
  packages/config/tsconfig.json
  packages/kcms/tsconfig.json
Labels: バグ/不具合, backend

#166 feat: バルクエントリーの実装
  packages/kcms/src/entry/main.ts
  packages/kcms/src/entry/schema.ts
Labels: backend

#176 fix: configの`target`を`ES2023`に修正
  packages/config/tsconfig.json
Labels: 改善, config

#191 feat: モックアップを作成
  package.json
  packages/mock/.gitignore
  packages/mock/.prettierignore
  packages/mock/.prettierrc
  packages/mock/README.md
  packages/mock/package.json
  packages/mock/src/data/main.ts
  packages/mock/src/data/match.ts
  packages/mock/src/data/runResult.ts
  packages/mock/src/data/team.ts
  packages/mock/src/main.ts
  packages/mock/tsconfig.json
  packages/mock/wrangler.toml
  pnpm-lock.yaml
Labels: 新機能
