Repository poporonnet/kcmsx, pull requests merged in 2024-07, with the labels that each got.

#42 feat: モノレポの整備
  .github/renovate.json
  .github/workflows/ci.yml
  package.json
  packages/kcms/README.md
  packages/kcms/bun.lockb
  packages/kcms/package.json
  packages/kcms/src/main.ts
  packages/kcms/tsconfig.json
  packages/kcms/vite.config.ts
  packages/kcmsf/renovate.json
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: frontend, backend

#72 fix: pnpm/action-setupをcorepackで置き換え
  .github/workflows/ci.yml
  package.json
Labels: backend

#77 refactor: モデルのゲッター/セッターを関数に置き換え
  packages/kcms/src/entry/adaptor/dummyRepository.ts
  packages/kcms/src/entry/adaptor/json.ts
  packages/kcms/src/entry/controller.ts
  packages/kcms/src/entry/entry.test.ts
  packages/kcms/src/entry/entry.ts
  packages/kcms/src/entry/service/entry.test.ts
  packages/kcms/src/entry/service/get.test.ts
  packages/kcms/src/entry/service/get.ts
  packages/kcms/src/match/adaptor/dummyRepository.ts
  packages/kcms/src/match/adaptor/json.ts
  packages/kcms/src/match/controller.ts
  packages/kcms/src/match/match.test.ts
  packages/kcms/src/match/match.ts
  packages/kcms/src/match/service/edit.ts
  packages/kcms/src/match/service/generateFinal.test.ts
  packages/kcms/src/match/service/generateFinal.ts
  packages/kcms/src/match/service/generatePrimary.test.ts
  packages/kcms/src/match/service/generatePrimary.ts
  packages/kcms/src/match/service/generateRanking.test.ts
  packages/kcms/src/match/service/generateRanking.ts
  packages/kcms/src/match/service/get.test.ts
  packages/kcms/src/match/service/get.ts
Labels: backend, 改善

#80 chore: `.gitignore`を追加
  .gitignore
Labels: frontend, backend

#78 feat(model): RunResult(走行結果)モデルを追加
  packages/kcms/src/match/adaptor/dummyRepository.ts
  packages/kcms/src/match/adaptor/json.ts
  packages/kcms/src/match/controller.ts
  packages/kcms/src/match/main.ts
  packages/kcms/src/match/model/match.test.ts
  packages/kcms/src/match/model/match.ts
  packages/kcms/src/match/model/runResult.test.ts
  packages/kcms/src/match/model/runResult.ts
  packages/kcms/src/match/service/edit.test.ts
  packages/kcms/src/match/service/edit.ts
  packages/kcms/src/match/service/generateFinal.test.ts
  packages/kcms/src/match/service/generateFinal.ts
  packages/kcms/src/match/service/generatePrimary.ts
  packages/kcms/src/match/service/generateRanking.ts
  packages/kcms/src/match/service/get.ts
  packages/kcms/src/match/service/repository.ts
  packages/kcms/src/testData/match.ts
Labels: 新機能, backend

#84 chore: ESLintの設定を修正・Flat Configに移行
  packages/kcms/.eslintrc.json
  packages/kcms/eslint.config.js
  packages/kcms/package.json
  packages/kcmsf/.eslintrc.cjs
  packages/kcmsf/.gitignore
  packages/kcmsf/eslint.config.js
  packages/kcmsf/package.json
  pnpm-lock.yaml
Labels: frontend, backend, 改善

#87 chore: フロントエンドのlintのwarning対応
  packages/kcmsf/src/hooks/useInterval.ts
Labels: frontend, 改善

#94 chore: サイトの言語を日本語に変更した
  packages/kcmsf/index.html
Labels: frontend, 改善

#93 chore:サイトのタイトルをデフォルトからkcmsxに変更した
  packages/kcmsf/index.html
Labels: frontend, 改善

#99 fix: `eslint-plugin-react-hooks`をeslint v9に対応させる
  packages/kcmsf/eslint.config.js
  packages/kcmsf/package.json
  pnpm-lock.yaml
Labels: frontend, 改善

#86 fix: 本戦試合(`MainMatch`)/予選試合(`PreMatch`)を定義
  packages/kcms/src/match/model/main.test.ts
  packages/kcms/src/match/model/main.ts
  packages/kcms/src/match/model/match.ts
  packages/kcms/src/match/model/pre.test.ts
  packages/kcms/src/match/model/pre.ts
  packages/kcms/src/match/service/generateFinal.ts
  packages/kcms/src/match/service/generatePrimary.ts
Labels: backend, 改善

#95 feat: 採点UIを設定オブジェクトから動的に生成するように変更
  packages/kcmsf/src/components/match/PointControl.tsx
  packages/kcmsf/src/components/match/PointControls.tsx
  packages/kcmsf/src/components/match/PointCountable.tsx
  packages/kcmsf/src/components/match/PointSingle.tsx
  packages/kcmsf/src/components/match/matchSubmit.tsx
  packages/kcmsf/src/components/pointControls.tsx
  packages/kcmsf/src/config/lang/lang.ts
  packages/kcmsf/src/config/rule/rule.ts
  packages/kcmsf/src/config/types/lang.ts
  packages/kcmsf/src/config/types/rule.ts
  packages/kcmsf/src/pages/match.tsx
  packages/kcmsf/src/utils/match/judge.ts
  packages/kcmsf/src/utils/match/point.ts
Labels: frontend, 改善

#144 chore(format): フロントエンドにフォーマットを掛けた
  packages/kcmsf/src/pages/matchList.tsx
  packages/kcmsf/tsconfig.json
Labels: frontend, 改善

#142 feat(ci): フロントエンドのフォーマットチェックを追加
  .github/workflows/ci.yml
  packages/kcmsf/package.json
Labels: frontend, 改善
