Repository poporonnet/kcmsx, pull requests merged in 2024-12, with the labels that each got.

#755 fix: LabeledSegmentedControlが適切な幅で表示される
  packages/kcmsf/src/components/LabeledSegmentedControl.tsx
  packages/kcmsf/src/components/LabeledSegmentedControls.tsx
  packages/kcmsf/src/pages/matchList.tsx
  packages/kcmsf/src/pages/ranking.tsx
Labels: バグ/不具合, frontend

#738 feat:ランキングの自動更新を制御
  packages/kcmsf/src/hooks/useInterval.ts
  packages/kcmsf/src/pages/ranking.tsx
  packages/mock/src/data/main.ts
  packages/mock/src/data/ranking.ts
  packages/mock/src/main.ts
Labels: frontend, 改善, mock

#762 fix: mockの本戦試合のidを修正
  packages/mock/src/data/match.ts
Labels: バグ/不具合, frontend, mock

#765 fix: 試合のステータスを正しく表示
  packages/kcmsf/src/pages/match.tsx
  packages/kcmsf/src/pages/matchList.tsx
  packages/kcmsf/src/utils/matchStatus.ts
Labels: バグ/不具合, frontend

#760 feat: トーナメント図の表示
  packages/kcmsf/package.json
  packages/kcmsf/src/App.css
  packages/kcmsf/src/components/tournament/MatchNode.tsx
  packages/kcmsf/src/components/tournament/TeamNode.tsx
  packages/kcmsf/src/components/tournament/TournamentBracket.tsx
  packages/kcmsf/src/components/tournament/tournament.module.css
  packages/kcmsf/src/components/tournament/tournamentContainer.css
  packages/kcmsf/src/hooks/useCenterTranslate.ts
  packages/kcmsf/src/hooks/useDepartmentTypeQuery.ts
  packages/kcmsf/src/hooks/useMatchTypeQuery.ts
  packages/kcmsf/src/hooks/useQueryParamsState.ts
  packages/kcmsf/src/hooks/useResizeObserver.ts
  packages/kcmsf/src/hooks/useTournamentData.ts
  packages/kcmsf/src/pages/home.tsx
  packages/kcmsf/src/pages/matchList.tsx
  packages/kcmsf/src/pages/ranking.tsx
  packages/kcmsf/src/pages/registerBulk.tsx
  packages/kcmsf/src/pages/result.tsx
  packages/kcmsf/src/pages/tournament.tsx
  packages/kcmsf/src/routes/layout.tsx
  packages/kcmsf/src/routes/router.tsx
  packages/kcmsf/src/types/tournament.ts
  packages/kcmsf/src/types/tournamentData.ts
  pnpm-lock.yaml
Labels: 新機能, frontend

#790 feat: 認証機能の実装
  docs/api.md
  packages/kcms/README.md
  packages/kcms/src/main.ts
  packages/mock/src/main.ts
Labels: ドキュメント, 新機能, backend

#789 feat: カラム全体をリンクに変更
  packages/kcmsf/src/components/matchStatus.tsx
  packages/kcmsf/src/pages/matchList.tsx
Labels: frontend, 改善

#800 chore: DummyRepositoryを使わない
  packages/kcms/src/match/main.ts
  packages/kcms/src/team/main.ts
Labels: backend, 改善

#807 chore:オープン部門に車輪型を追加
  packages/config/src/config.ts
Labels: 改善, config

#801 feat: フロントエンドに認証を追加
  packages/kcms/README.md
  packages/kcms/src/main.ts
  packages/kcmsf/src/App.tsx
  packages/kcmsf/src/components/AuthProvider.tsx
  packages/kcmsf/src/components/Login.tsx
  packages/kcmsf/src/components/match/matchSubmit.tsx
  packages/kcmsf/src/hooks/useAuth.ts
  packages/kcmsf/src/hooks/useFetch.ts
  packages/kcmsf/src/hooks/useMatchInfo.ts
  packages/kcmsf/src/pages/matchList.tsx
  packages/kcmsf/src/pages/ranking.tsx
  packages/kcmsf/src/pages/register.tsx
  packages/kcmsf/src/pages/registerBulk.tsx
  packages/kcmsf/src/pages/teams.tsx
  packages/mock/src/main.ts
Labels: 新機能, frontend, backend

#818 feat: 試合が使用するコースをコース番号で設定する
  packages/config/README.md
  packages/config/src/config.ts
  packages/config/src/types/matchConfig.ts
  packages/config/src/utility/createConfig.test.ts
  packages/config/src/utility/createConfig.ts
  packages/kcms/src/match/service/generatePre.test.ts
  packages/kcms/src/match/service/generatePre.ts
Labels: 改善, config

#751 chore: MainMatchに前後の試合情報を追加
  packages/kcms/prisma/migrations/20241128065421_add_parent_children_relation/migration.sql
  packages/kcms/prisma/migrations/20241201141958_add_children_left_right/migration.sql
  packages/kcms/prisma/migrations/20241201142436_remove_children_matches/migration.sql
  packages/kcms/prisma/migrations/20241209084653_recreate_mainmatch_relation/migration.sql
  packages/kcms/prisma/migrations/20241211040330_rename_children_match_to_child_match/migration.sql
  packages/kcms/prisma/schema.prisma
  packages/kcms/src/match/adaptor/dummy/mainMatchRepository.test.ts
  packages/kcms/src/match/adaptor/prisma/mainMatchRepository.ts
  packages/kcms/src/match/model/main.test.ts
  packages/kcms/src/match/model/main.ts
  packages/kcms/src/match/service/generateMain.ts
  packages/kcms/src/testData/match.ts
Labels: backend, 改善

#798 fix: チームのメンバーに空文字列が登録できないようにする
  packages/kcms/src/team/adaptor/validator/team.ts
  packages/kcmsf/src/components/CsvExample.tsx
  packages/kcmsf/src/hooks/useCheckData.ts
  packages/kcmsf/src/pages/registerBulk.tsx
Labels: バグ/不具合, frontend, backend

#820 feat: 試合種別を`pre`と`main`で固定
  packages/config/README.md
  packages/config/src/config.ts
  packages/config/src/types/conditionsConfig.ts
  packages/config/src/types/config.ts
  packages/config/src/types/matchConfig.ts
  packages/config/src/types/ruleList.ts
  packages/config/src/utility/createConfig.test.ts
  packages/config/src/utility/createConfig.ts
Labels: 改善, config

#828 refactor: 関数名や変数名のIdをIDに変更した
  packages/kcms/prisma/schema.prisma
  packages/kcms/src/id/main.ts
  packages/kcms/src/match/adaptor/controller/match.ts
  packages/kcms/src/match/adaptor/dummy/mainMatchRepository.test.ts
  packages/kcms/src/match/adaptor/dummy/mainMatchRepository.ts
  packages/kcms/src/match/adaptor/dummy/preMatchRepository.test.ts
  packages/kcms/src/match/adaptor/dummy/preMatchRepository.ts
  packages/kcms/src/match/adaptor/prisma/mainMatchRepository.ts
  packages/kcms/src/match/adaptor/prisma/preMatchRepository.ts
  packages/kcms/src/match/adaptor/validator/match.ts
  packages/kcms/src/match/main.ts
  packages/kcms/src/match/model/main.test.ts
  packages/kcms/src/match/model/main.ts
  packages/kcms/src/match/model/pre.test.ts
  packages/kcms/src/match/model/pre.ts
  packages/kcms/src/match/model/runResult.test.ts
  packages/kcms/src/match/model/runResult.ts
  packages/kcms/src/match/routing.ts
  packages/kcms/src/match/service/createRunResult.test.ts
  packages/kcms/src/match/service/generateMain.test.ts
  packages/kcms/src/match/service/generateMain.ts
  packages/kcms/src/match/service/generatePre.test.ts
  packages/kcms/src/match/service/generatePre.ts
  packages/kcms/src/match/service/generateRanking.ts
  packages/kcms/src/match/service/get.test.ts
  packages/kcms/src/match/service/get.ts
  packages/kcms/src/team/adaptor/controller/controller.ts
  packages/kcms/src/team/adaptor/repository/dummyRepository.ts
  packages/kcms/src/team/adaptor/repository/prismaRepository.ts
  packages/kcms/src/team/models/team.test.ts
  packages/kcms/src/team/models/team.ts
  packages/kcms/src/team/service/entry.test.ts
  packages/kcms/src/team/service/fetchTeam.test.ts
  packages/kcms/src/testData/entry.ts
  packages/kcms/src/testData/match.ts
  packages/kcmsf/src/components/match/matchSubmit.tsx
  packages/kcmsf/src/components/tournament/MatchNode.tsx
  packages/kcmsf/src/components/tournament/TournamentBracket.tsx
  packages/kcmsf/src/hooks/useForceReload.ts
  packages/kcmsf/src/hooks/useInterval.ts
  packages/kcmsf/src/hooks/useTournamentData.ts
  packages/kcmsf/src/pages/result.tsx
  packages/kcmsf/src/pages/tournament.tsx
  packages/kcmsf/src/types/match.ts
  packages/kcmsf/src/types/tournament.ts
  packages/kcmsf/src/types/tournamentData.ts
Labels: frontend, backend
