Repository poporonnet/kcmsx, pull requests merged in 2024-10, with the labels that each got.

#288 feat: 予選対戦表の生成ができるように
  packages/kcms/src/match/model/pre.ts
  packages/kcms/src/match/service/generatePre.test.ts
  packages/kcms/src/match/service/generatePre.ts
  packages/kcms/src/team/controller.ts
  packages/kcms/src/team/main.ts
  packages/kcms/src/team/models/team.test.ts
  packages/kcms/src/team/models/team.ts
  packages/kcms/src/team/service/createTeam.test.ts
  packages/kcms/src/team/service/createTeam.ts
  packages/kcms/src/team/service/get.test.ts
  packages/kcms/src/team/service/get.ts
  packages/kcms/src/testData/entry.ts
Labels: backend

#365 feat: Prismaを使うRepository を実装した
  packages/kcms/package.json
  packages/kcms/src/match/adaptor/prisma/mainMatchRepository.ts
  packages/kcms/src/match/adaptor/prisma/preMatchRepository.ts
  packages/kcms/src/match/service/generatePre.test.ts
  packages/kcms/src/team/adaptor/repository/dummyRepository.ts
  packages/kcms/src/team/adaptor/repository/prismaRepository.ts
  packages/kcms/src/team/main.ts
  packages/kcms/src/team/service/createTeam.test.ts
  packages/kcms/src/team/service/delete.test.ts
  packages/kcms/src/team/service/entry.test.ts
  packages/kcms/src/team/service/get.test.ts
  pnpm-lock.yaml
Labels: backend

#373 fix: Pagesのプレビュービルドからもmockが使えるように修正
  packages/mock/src/main.ts
  packages/mock/wrangler.toml
Labels: 改善, mock

#370 feat:試合一覧取得のスキーマを定義
  packages/kcms/src/match/adaptor/validator/match.ts
  packages/kcms/src/match/routing.ts
  packages/kcms/src/team/routing.ts
Labels: 新機能, backend

#375 feat: 不要なメンバ変数を除去
  packages/kcms/src/main.ts
  packages/kcms/src/match/adaptor/prisma/mainMatchRepository.ts
  packages/kcms/src/team/adaptor/repository/prismaRepository.ts
  packages/kcms/src/team/controller.ts
  packages/kcms/src/team/main.ts
  packages/kcms/src/team/models/team.test.ts
  packages/kcms/src/team/models/team.ts
  packages/kcms/src/team/service/createTeam.test.ts
  packages/kcms/src/team/service/createTeam.ts
  packages/kcms/src/testData/entry.ts
Labels: backend, 改善

#369 chore:14 試合へのstate渡しをパスパラメーターに変更
  packages/kcmsf/src/components/linkToMatch.tsx
  packages/kcmsf/src/components/matchStatus.tsx
  packages/kcmsf/src/pages/match.tsx
  packages/kcmsf/src/pages/matchList.tsx
  packages/kcmsf/src/pages/ranking.css
  packages/kcmsf/src/pages/ranking.tsx
  packages/kcmsf/src/pages/result.css
  packages/kcmsf/src/pages/result.tsx
  packages/kcmsf/src/routes/router.tsx
  packages/kcmsf/src/types/match.ts
Labels: frontend, 改善

#386 feat: チーム登録の実装, Nodeで実行できない問題への暫定対応
  packages/kcms/package.json
  packages/kcms/prisma/migrations/20241003090116_add_unique_team_name/migration.sql
  packages/kcms/prisma/schema.prisma
  packages/kcms/src/adaptor.ts
  packages/kcms/src/main.ts
  packages/kcms/src/team/adaptor/repository/prismaRepository.ts
  packages/kcms/src/team/controller.ts
  packages/kcms/src/team/main.ts
  packages/kcms/src/team/service/createTeam.test.ts
  packages/kcms/src/team/service/createTeam.ts
Labels: バグ/不具合, 新機能, backend

#401 feat: チーム登録を新APIに対応させた
  packages/kcms/src/team/controller.ts
  packages/kcms/src/team/service/createTeam.ts
  packages/kcmsf/README.md
  packages/kcmsf/src/pages/entry.tsx
  packages/kcmsf/src/pages/register.tsx
  packages/kcmsf/src/pages/registerBulk.tsx
  packages/kcmsf/src/routes/router.tsx
  packages/kcmsf/src/types/entry.ts
Labels: バグ/不具合, backend, 改善

#374 fix: チーム一覧ページを修正
  packages/kcmsf/README.md
  packages/kcmsf/package.json
  packages/kcmsf/src/components/Filter.tsx
  packages/kcmsf/src/components/LoaderButton.tsx
  packages/kcmsf/src/components/Sort.tsx
  packages/kcmsf/src/components/header.test.tsx
  packages/kcmsf/src/components/header.tsx
  packages/kcmsf/src/pages/entryList.css
  packages/kcmsf/src/pages/entryList.tsx
  packages/kcmsf/src/pages/home.tsx
  packages/kcmsf/src/pages/teams.tsx
  packages/kcmsf/src/routes/router.tsx
  pnpm-lock.yaml
Labels: frontend, 改善

#411 fix: 試合の終了条件にフィニッシュを含める
  packages/kcmsf/src/pages/match.tsx
Labels: frontend, 改善

#415 feat: ロボットの設定で表示名を記述できる
  packages/config/README.md
  packages/config/src/config.ts
  packages/config/src/types/conditionsConfig.ts
  packages/config/src/types/config.ts
  packages/config/src/types/departmentConfig.ts
  packages/config/src/types/matchConfig.ts
  packages/config/src/types/robotConfig.ts
  packages/config/src/types/ruleList.ts
  packages/config/src/utility/createConfig.test.ts
  packages/config/src/utility/createConfig.ts
  packages/config/src/utility/pick.ts
Labels: 新機能, 改善, config

#416 feat: ヘッダーにトップへのリンクを設置
  packages/kcmsf/src/components/header.tsx
Labels: frontend, 改善

#419 fix: `TeamInfo`のプロパティを`robotType`と`departmentType`に変更
  packages/config/src/types/conditionsConfig.ts
  packages/config/src/types/derived/matchInfo.ts
  packages/config/src/types/derived/premise.ts
  packages/config/src/types/matchInfo.ts
  packages/config/src/types/premise.ts
  packages/config/src/types/rule.ts
  packages/config/src/utility/createConfig.test.ts
  packages/kcmsf/src/pages/match.tsx
Labels: frontend, 改善, config

#420 feat: エキシビションマッチで歩行型かどうかを入力できる
  packages/config/src/config.ts
  packages/kcmsf/src/pages/match.tsx
Labels: frontend, 改善, config

#423 fix: 本戦試合を表示できる
  packages/kcmsf/src/pages/match.tsx
Labels: バグ/不具合, frontend

#430 feat: MatchAPI.getAllMatchを実装
  packages/kcms/src/main.ts
  packages/kcms/src/match/adaptor/controller/match.ts
  packages/kcms/src/match/adaptor/validator/match.ts
  packages/kcms/src/match/main.ts
Labels: backend

#448 feat: 試合取得エンドポイントを実装
  packages/kcms/src/match/adaptor/controller/match.ts
  packages/kcms/src/match/adaptor/validator/match.ts
  packages/kcms/src/match/main.ts
Labels: 新機能, backend

#447 feat: 試合生成エンドポイントを実装
  packages/kcms/src/match/adaptor/controller/match.ts
  packages/kcms/src/match/adaptor/validator/match.ts
  packages/kcms/src/match/main.ts
  packages/kcms/src/match/routing.ts
Labels: 新機能, backend

#450 refactor: 古いディレクトリ構造を更新
  packages/kcms/src/main.ts
  packages/kcms/src/match/main.ts
  packages/kcms/src/team/adaptor/controller/controller.ts
  packages/kcms/src/team/main.ts
  packages/kcms/src/team/schema.ts
Labels: backend, 改善

#456 chore: `prettier-plugin-organize-imports`を導入
  packages/kcms/.prettierrc.json
  packages/kcms/eslint.config.js
  packages/kcms/package.json
  packages/kcms/src/id/main.test.ts
  packages/kcms/src/main.ts
  packages/kcms/src/match/adaptor/controller/match.ts
  packages/kcms/src/match/adaptor/dummy/mainMatchRepository.test.ts
  packages/kcms/src/match/adaptor/dummy/mainMatchRepository.ts
  packages/kcms/src/match/adaptor/dummy/preMatchRepository.test.ts
  packages/kcms/src/match/adaptor/dummy/preMatchRepository.ts
  packages/kcms/src/match/adaptor/prisma/mainMatchRepository.ts
  packages/kcms/src/match/adaptor/prisma/preMatchRepository.ts
  packages/kcms/src/match/main.ts
  packages/kcms/src/match/model/main.test.ts
  packages/kcms/src/match/model/main.ts
  packages/kcms/src/match/model/pre.test.ts
  packages/kcms/src/match/model/pre.ts
  packages/kcms/src/match/model/repository.ts
  packages/kcms/src/match/model/runResult.test.ts
  packages/kcms/src/match/routing.ts
  packages/kcms/src/match/service/fetchRunResult.test.ts
  packages/kcms/src/match/service/fetchRunResult.ts
  packages/kcms/src/match/service/generatePre.test.ts
  packages/kcms/src/match/service/generatePre.ts
  packages/kcms/src/match/service/get.test.ts
  packages/kcms/src/match/service/get.ts
  packages/kcms/src/team/adaptor/controller/controller.ts
  packages/kcms/src/team/adaptor/errors.test.ts
  packages/kcms/src/team/adaptor/repository/dummyRepository.ts
  packages/kcms/src/team/adaptor/repository/prismaRepository.ts
  packages/kcms/src/team/main.ts
  packages/kcms/src/team/models/repository.ts
  packages/kcms/src/team/models/team.ts
  packages/kcms/src/team/routing.ts
  packages/kcms/src/team/service/createTeam.test.ts
  packages/kcms/src/team/service/createTeam.ts
  packages/kcms/src/team/service/delete.test.ts
  packages/kcms/src/team/service/delete.ts
  packages/kcms/src/team/service/entry.test.ts
  packages/kcms/src/team/service/entry.ts
  packages/kcms/src/team/service/fetchTeam.test.ts
  packages/kcms/src/team/service/fetchTeam.ts
  packages/kcms/src/team/service/get.test.ts
  packages/kcms/src/team/service/get.ts
  packages/kcms/src/testData/entry.ts
  packages/kcms/src/testData/match.ts
  pnpm-lock.yaml
Labels: backend, 改善

#457 feat: エントリーができるように(Controller/Handlerの実装)
  packages/kcms/src/team/adaptor/controller/controller.ts
  packages/kcms/src/team/main.ts
Labels: 新機能, backend

#460 fix: チームが片方しかいない試合が表示できるように修正
  packages/config/src/config.ts
  packages/config/src/types/matchInfo.ts
  packages/config/src/types/premise.ts
  packages/config/src/utility/createConfig.test.ts
  packages/kcmsf/src/components/match/PointControl.tsx
  packages/kcmsf/src/components/match/PointControls.tsx
  packages/kcmsf/src/components/match/matchSubmit.tsx
  packages/kcmsf/src/pages/match.tsx
Labels: バグ/不具合, frontend

#459 feat: 試合種別の取得の実装
  packages/kcms/src/match/adaptor/controller/match.ts
  packages/kcms/src/match/adaptor/validator/match.ts
  packages/kcms/src/match/main.ts
  packages/kcms/src/match/model/main.ts
Labels: 新機能, backend

#463 feat: APIドキュメントページを追加
  packages/kcms/package.json
  packages/kcms/src/match/main.ts
  packages/kcms/src/team/main.ts
  pnpm-lock.yaml
Labels: backend, 改善

#470 chore: `@tabler/icons-react`を3.17.0にダウングレード
  packages/kcmsf/package.json
  pnpm-lock.yaml
Labels: frontend

#476 fix: `departmentType`をconfigの値と一致させる
  packages/mock/src/data/match.ts
  packages/mock/src/data/team.ts
Labels: バグ/不具合, mock

#474 fix: エキシビションマッチでは採点UIを無効化しないように修正
  packages/kcmsf/src/pages/match.tsx
Labels: バグ/不具合, frontend

#475 chore: フロントエンド用API型定義を作成
  packages/kcmsf/src/pages/matchList.tsx
  packages/kcmsf/src/pages/registerBulk.tsx
  packages/kcmsf/src/types/api/contest.ts
  packages/kcmsf/src/types/api/match.ts
  packages/kcmsf/src/types/api/sponsor.ts
  packages/kcmsf/src/types/api/team.ts
  packages/kcmsf/src/types/contest.ts
  packages/kcmsf/src/types/entry.ts
  packages/kcmsf/src/types/match.ts
  packages/kcmsf/src/types/runResult.ts
  packages/kcmsf/src/types/sponsor.ts
  packages/kcmsf/src/types/team.ts
Labels: frontend, 改善

#464 feat: ランキング生成APIの実装
  packages/kcms/src/match/adaptor/controller/match.ts
  packages/kcms/src/match/adaptor/validator/match.ts
  packages/kcms/src/match/main.ts
  packages/kcms/src/match/service/generateRanking.test.ts
  packages/kcms/src/match/service/generateRanking.ts
  packages/kcms/src/testData/match.ts
Labels: 新機能, backend

#483 feat: 著作権表記を更新
  packages/kcmsf/src/routes/layout.tsx
Labels: frontend

#487 fix: エキシビションマッチでも得点が正しく表示されるように
  packages/kcmsf/src/pages/match.tsx
Labels: バグ/不具合, frontend

#488 fix: 左右入れ替えの片方しか終了していない場合でも予選ランキングが正しく計算されるように修正
  packages/kcms/src/match/service/generateRanking.ts
  packages/kcms/src/testData/match.ts
  packages/kcmsf/src/pages/match.tsx
Labels: バグ/不具合, backend

#482 feat: ランキング画面
  packages/kcmsf/src/pages/ranking.tsx
  packages/kcmsf/src/routes/router.tsx
Labels: 新機能, frontend

#489 fix: `goalTimeSeconds`が0の時も正しくランキングを表示できるように修正
  packages/kcmsf/src/pages/ranking.tsx
Labels: バグ/不具合, frontend

#517 chore: 各ページで定義していた型をAPI型定義に置き換えた
  packages/kcmsf/src/pages/match.tsx
  packages/kcmsf/src/pages/register.tsx
  packages/kcmsf/src/pages/result.tsx
  packages/kcmsf/src/pages/teams.tsx
  packages/kcmsf/src/types/match.ts
Labels: frontend, 改善

#520 feat: 得点リセットボタン
  packages/kcmsf/src/components/match/PointControl.tsx
  packages/kcmsf/src/components/match/PointCountable.tsx
  packages/kcmsf/src/components/match/PointSingle.tsx
  packages/kcmsf/src/pages/match.tsx
  packages/kcmsf/src/utils/match/point.ts
  packages/kcmsf/src/utils/match/team.ts
Labels: 新機能, frontend

#521 fix: 本戦のみ先ゴールに1点を与えるように修正
  packages/config/src/config.ts
Labels: バグ/不具合, config

#513 feat: 試合生成ボタン
  packages/kcmsf/src/components/courseSelector.tsx
  packages/kcmsf/src/index.css
  packages/kcmsf/src/pages/matchList.tsx
  packages/kcmsf/src/pages/teams.tsx
Labels: 新機能, frontend

#526 feat: 指定した試合の走行結果を実装
  packages/kcms/src/match/adaptor/controller/match.ts
  packages/kcms/src/match/main.ts
Labels: 新機能, backend

#525 feat: PreMatchのAPIに`matchType`を追加した
  docs/api.md
  packages/kcms/src/match/adaptor/controller/match.ts
  packages/kcms/src/match/adaptor/validator/match.ts
  packages/kcmsf/src/types/match.ts
  packages/mock/src/data/match.ts
Labels: frontend, backend, 改善

#527 fix:goalTimeSecondsのInfinityを変換
  packages/kcms/src/match/adaptor/prisma/mainMatchRepository.ts
  packages/kcms/src/match/adaptor/prisma/preMatchRepository.ts
Labels: バグ/不具合, backend

#510 feat: 本戦試合生成Serviceの実装とテスト
  packages/kcms/src/match/service/generateMain.test.ts
  packages/kcms/src/match/service/generateMain.ts
Labels: 新機能, backend

#550 chore: `index.ts`を移動
  packages/config/index.ts
  packages/config/package.json
  packages/config/src/index.ts
Labels: 改善, config

#552 feat: 本戦試合生成のリクエストを送信する
  packages/kcmsf/src/pages/ranking.tsx
  packages/kcmsf/src/types/api/match.ts
  packages/kcmsf/src/types/match.ts
Labels: 新機能, frontend

#562 feat: 試合の取得(`GET /match`, `GET /match/{matchType}/{matchID}`)でMainMatchも取得する
  packages/kcms/src/match/adaptor/controller/match.ts
Labels: backend, 改善

#565 fix: 本戦試合生成リクエストのヘッダに`"Content-Type": "application/json"`を追加
  packages/kcmsf/src/pages/ranking.tsx
Labels: バグ/不具合, frontend

#572 feat: 試合一覧ページで本戦試合を表示する
  packages/kcmsf/src/components/DepartmentSegmentedControl.tsx
  packages/kcmsf/src/components/LabeledSegmentedControl.tsx
  packages/kcmsf/src/components/MatchTypeSegmentedControl.tsx
  packages/kcmsf/src/components/matchStatus.tsx
  packages/kcmsf/src/pages/matchList.tsx
  packages/kcmsf/src/pages/ranking.tsx
Labels: 新機能, frontend

#578 feat: 試合一覧ページの試合生成ボタンを予選選択時にしか押せないように
  packages/kcmsf/src/pages/matchList.tsx
Labels: frontend, 改善

#576 feat: 本戦試合が存在しているときは本戦試合を生成できないように
  packages/kcmsf/src/components/GenerateMainMatchCard.tsx
  packages/kcmsf/src/pages/ranking.tsx
Labels: frontend, 改善

#581 fix: 本戦試合が存在することを見る条件式を正しいものに修正
  packages/kcmsf/src/components/GenerateMainMatchCard.tsx
Labels: バグ/不具合, frontend

#579 feat: (安来用)本戦試合のランキングを取得できる
  packages/kcms/src/match/adaptor/controller/match.ts
  packages/kcms/src/match/main.ts
  packages/kcms/src/match/service/generateRanking.test.ts
  packages/kcms/src/match/service/generateRanking.ts
  packages/kcms/src/testData/match.ts
Labels: 新機能, backend

#570 fix:試合結果のゴールタイムの表示を修正した
  packages/kcmsf/src/pages/result.tsx
  packages/mock/src/data/match.ts
  packages/mock/src/data/runResult.ts
Labels: バグ/不具合, frontend

#582 chore: パス末尾のスラッシュを削除する
  packages/kcms/src/main.ts
Labels: backend, 改善

#573 fix:MainMatchに走行結果を追加できるよう変更
  packages/kcms/src/match/adaptor/prisma/mainMatchRepository.ts
  packages/kcms/src/match/adaptor/prisma/preMatchRepository.ts
  packages/kcms/src/match/model/main.test.ts
  packages/kcms/src/match/model/main.ts
Labels: バグ/不具合, backend

#584 fix: 予選ランキングにしかチェックボックスを表示しないように
  packages/kcmsf/src/pages/ranking.tsx
Labels: frontend, 改善

#598 feat: 本戦試合2回目を考慮した表示
  packages/kcmsf/src/components/match/matchSubmit.tsx
  packages/kcmsf/src/hooks/useJudge.ts
  packages/kcmsf/src/hooks/useMatchInfo.ts
  packages/kcmsf/src/hooks/useMatchTimer.ts
  packages/kcmsf/src/pages/match.tsx
Labels: frontend, 改善

#606 Revert "chore(deps): update dependency @tabler/icons-react to v3.20.0"
  packages/kcmsf/package.json
  pnpm-lock.yaml
Labels: frontend

#612 feat: ローカルホスティングのための機能を追加
  packages/kcms/package.json
  packages/kcmsf/.env.production
  packages/kcmsf/README.md
  packages/kcmsf/package.json
  pnpm-lock.yaml
Labels: 新機能, frontend, backend

#614 refactor: データフェッチをカスタムフック化
  packages/kcmsf/src/components/GenerateMainMatchCard.tsx
  packages/kcmsf/src/hooks/useFetch.ts
  packages/kcmsf/src/pages/matchList.tsx
  packages/kcmsf/src/pages/ranking.tsx
  packages/kcmsf/src/pages/result.tsx
  packages/kcmsf/src/pages/teams.tsx
  packages/kcmsf/tsconfig.json
Labels: frontend, 改善

#641 fix:ランキングで同順位がいる場合の順位表示の修正
  packages/kcms/src/match/service/generateRanking.test.ts
  packages/kcms/src/match/service/generateRanking.ts
Labels: backend

#646 chore:チーム取得サービスを統合する
  packages/kcms/src/match/adaptor/controller/match.ts
  packages/kcms/src/match/main.ts
  packages/kcms/src/match/service/generatePre.test.ts
  packages/kcms/src/match/service/generatePre.ts
  packages/kcms/src/team/adaptor/controller/controller.ts
  packages/kcms/src/team/main.ts
  packages/kcms/src/team/service/fetchTeam.test.ts
  packages/kcms/src/team/service/fetchTeam.ts
  packages/kcms/src/team/service/get.test.ts
  packages/kcms/src/team/service/get.ts
Labels: backend
