Repository poporonnet/kcmsx, pull requests merged in 2024-09, with the labels that each got.

#233 docs:新規コントリビューター向けのドキュメントを作った
  docs/api.md
  docs/conflict.png
  docs/development.md
  docs/gh-action-test.png
  docs/httpie.md
  docs/httpie.png
  docs/pullrequest.png
Labels: ドキュメント

#244 fix: FinishStateの変更
  packages/kcms/src/match/model/runResult.test.ts
  packages/kcms/src/match/model/runResult.ts
Labels: backend

#276 feat: リテラルオブジェクトの配列から型安全に`map`をする`pick`を追加
  packages/config/README.md
  packages/config/eslint.config.js
  packages/config/index.ts
  packages/config/package.json
  packages/config/src/utility/pick.test-d.ts
  packages/config/src/utility/pick.test.ts
  packages/config/src/utility/pick.ts
Labels: 新機能, config

#271 feat: フィニッシュを実装
  packages/config/src/config.ts
  packages/kcmsf/.env
  packages/kcmsf/.env.development
  packages/kcmsf/.env.staging
  packages/kcmsf/src/components/match/matchSubmit.tsx
  packages/mock/src/main.ts
Labels: 新機能, frontend

#272 feat: スポンサーのconfigを追加
  packages/config/README.md
  packages/config/src/config.ts
  packages/config/src/types/config.ts
  packages/config/src/types/sponsorConfig.ts
  packages/config/src/utility/createConfig.test.ts
  packages/config/src/utility/createConfig.ts
Labels: 新機能, config

#274 feat:TeamsSchemaを追加
  packages/kcms/package.json
  packages/kcms/src/entry/adaptor/validator/team.ts
  packages/kcms/src/entry/routing.ts
  pnpm-lock.yaml
Labels: backend

#171 refactor: Matchモデルの分割で生じた不具合を修正/足りない部分は再実装した
  packages/kcms/src/entry/repository.ts
  packages/kcms/src/main.ts
  packages/kcms/src/match/adaptor/dummy/mainMatchRepository.test.ts
  packages/kcms/src/match/adaptor/dummy/mainMatchRepository.ts
  packages/kcms/src/match/adaptor/dummy/preMatchRepository.test.ts
  packages/kcms/src/match/adaptor/dummy/preMatchRepository.ts
  packages/kcms/src/match/adaptor/dummyRepository.ts
  packages/kcms/src/match/adaptor/json.ts
  packages/kcms/src/match/controller.ts
  packages/kcms/src/match/main.ts
  packages/kcms/src/match/model/main.test.ts
  packages/kcms/src/match/model/main.ts
  packages/kcms/src/match/model/match.test.ts
  packages/kcms/src/match/model/match.ts
  packages/kcms/src/match/model/pre.test.ts
  packages/kcms/src/match/model/pre.ts
  packages/kcms/src/match/model/repository.ts
  packages/kcms/src/match/model/runResult.test.ts
  packages/kcms/src/match/model/runResult.ts
  packages/kcms/src/match/service/edit.test.ts
  packages/kcms/src/match/service/edit.ts
  packages/kcms/src/match/service/generateFinal.test.ts
  packages/kcms/src/match/service/generateFinal.ts
  packages/kcms/src/match/service/generatePrimary.test.ts
  packages/kcms/src/match/service/generatePrimary.ts
  packages/kcms/src/match/service/generateRanking.test.ts
  packages/kcms/src/match/service/generateRanking.ts
  packages/kcms/src/match/service/get.test.ts
  packages/kcms/src/match/service/get.ts
  packages/kcms/src/match/service/repository.ts
  packages/kcms/src/match/tournament.ts
  packages/kcms/src/team/adaptor/dummyRepository.ts
  packages/kcms/src/team/adaptor/errors.test.ts
  packages/kcms/src/team/adaptor/errors.ts
  packages/kcms/src/team/adaptor/json.ts
  packages/kcms/src/team/controller.ts
  packages/kcms/src/team/main.ts
  packages/kcms/src/team/models/repository.ts
  packages/kcms/src/team/models/team.test.ts
  packages/kcms/src/team/models/team.ts
  packages/kcms/src/team/schema.ts
  packages/kcms/src/team/service/delete.test.ts
  packages/kcms/src/team/service/delete.ts
  packages/kcms/src/team/service/entry.test.ts
  packages/kcms/src/team/service/entry.ts
  packages/kcms/src/team/service/get.test.ts
  packages/kcms/src/team/service/get.ts
  packages/kcms/src/testData/entry.ts
  packages/kcms/src/testData/match.ts
Labels: backend, 改善

#284 feat: `post /team`のスキーマとルートを定義
  docs/api.md
  packages/kcms/src/entry/routing.ts
  packages/kcms/src/team/adaptor/validator/team.ts
  packages/kcms/src/team/routing.ts
Labels: backend

#287 feat: コース数のconfig
  packages/config/README.md
  packages/config/src/config.ts
  packages/config/src/types/matchConfig.ts
  packages/config/src/utility/createConfig.test.ts
  packages/config/src/utility/createConfig.ts
Labels: 新機能, config

#283 feat: 出欠確認(エントリー)ができるように
  packages/kcms/src/team/adaptor/dummyRepository.ts
  packages/kcms/src/team/adaptor/json.ts
  packages/kcms/src/team/controller.ts
  packages/kcms/src/team/main.ts
  packages/kcms/src/team/models/repository.ts
  packages/kcms/src/team/models/team.test.ts
  packages/kcms/src/team/models/team.ts
  packages/kcms/src/team/service/createTeam.test.ts
  packages/kcms/src/team/service/createTeam.ts
  packages/kcms/src/team/service/delete.ts
  packages/kcms/src/team/service/entry.test.ts
  packages/kcms/src/team/service/entry.ts
  packages/kcms/src/team/service/get.ts
  packages/kcms/src/testData/entry.ts
Labels: 新機能, backend

#285 feat:``delete /team/{teamid}``のスキーマとルートを定義
  packages/kcms/src/team/adaptor/validator/team.ts
  packages/kcms/src/team/routing.ts
Labels: backend
