Repository poporonnet/kcmsx, pull requests merged in 2025-01, with the labels that each got.

#831 feat: 試合参加チーム数を設定できる
  packages/config/README.md
  packages/config/src/config.ts
  packages/config/src/types/matchConfig.ts
  packages/config/src/utility/createConfig.test.ts
  packages/config/src/utility/createConfig.ts
Labels: 新機能, config

#862 feat: 本戦生成時に順位をドラッグアンドドロップで決定できる
  packages/config/src/config.ts
  packages/kcmsf/package.json
  packages/kcmsf/src/components/AuthProvider.tsx
  packages/kcmsf/src/components/GenerateMainMatchCard.tsx
  packages/kcmsf/src/components/LabeledSegmentedControls.tsx
  packages/kcmsf/src/components/Login.tsx
  packages/kcmsf/src/contexts/AuthContext.ts
  packages/kcmsf/src/hooks/useAuth.ts
  packages/kcmsf/src/pages/ranking.tsx
  pnpm-lock.yaml
Labels: 新機能, frontend

#879 feat: 試合一覧ページで部門を選択できる
  packages/kcmsf/src/pages/matchList.tsx
Labels: 新機能, frontend

#861 feat!(api,service): 本戦試合生成をトーナメント方式に変更
  packages/kcms/src/match/adaptor/controller/match.ts
  packages/kcms/src/match/adaptor/validator/match.ts
  packages/kcms/src/match/main.ts
  packages/kcms/src/match/model/main.ts
  packages/kcms/src/match/service/generateMain.test.ts
  packages/kcms/src/match/service/generateMain.ts
  packages/kcms/src/match/utility/eachSlice.test.ts
  packages/kcms/src/match/utility/eachSlice.ts
Labels: help wanted, backend, 改善

#871 feat: 本戦トーナメント取得(`GET /match/main/{departmentType}/tournament`)を実装
  packages/kcms/prisma/schema.prisma
  packages/kcms/src/match/adaptor/controller/match.ts
  packages/kcms/src/match/adaptor/validator/match.ts
  packages/kcms/src/match/main.ts
  packages/kcms/src/match/routing.ts
  packages/kcms/src/match/service/fetchTournament.test.ts
  packages/kcms/src/match/service/fetchTournament.ts
Labels: 新機能, backend

#881 chore: 最新のルールにconfigを対応させた
  packages/config/src/config.ts
  packages/kcms/src/match/service/generateMain.test.ts
  packages/kcms/src/match/service/generatePre.test.ts
Labels: backend, config

#875 feat: 実際の本戦トーナメント図を表示
  packages/kcmsf/src/components/tournament/MatchNode.tsx
  packages/kcmsf/src/components/tournament/TeamNode.tsx
  packages/kcmsf/src/components/tournament/TournamentBracket.tsx
  packages/kcmsf/src/hooks/useFetch.ts
  packages/kcmsf/src/hooks/useMatchInfo.ts
  packages/kcmsf/src/hooks/useTournamentData.ts
  packages/kcmsf/src/pages/result.tsx
  packages/kcmsf/src/pages/tournament.tsx
  packages/kcmsf/src/types/api/match.ts
  packages/kcmsf/src/types/match.ts
  packages/kcmsf/src/types/tournament.ts
  packages/kcmsf/src/types/tournamentData.ts
Labels: 新機能, frontend

#877 feat: 新しい本戦試合生成APIに対応
  packages/kcmsf/src/components/GenerateMainMatchCard.tsx
  packages/kcmsf/src/pages/ranking.tsx
  packages/kcmsf/src/types/match.ts
Labels: frontend, 改善

#885 fix: 試合のチームが空の場合に対応
  packages/kcms/src/match/adaptor/controller/match.ts
Labels: バグ/不具合, backend

#884 feat: エントリーコード(ゼッケン)
  packages/kcms/prisma/migrations/20250110025452_add_team_entry_code/migration.sql
  packages/kcms/prisma/schema.prisma
  packages/kcms/src/team/adaptor/controller/controller.ts
  packages/kcms/src/team/adaptor/repository/prismaRepository.ts
  packages/kcms/src/team/main.ts
  packages/kcms/src/team/models/team.test.ts
  packages/kcms/src/team/models/team.ts
  packages/kcms/src/team/service/entryCode.test.ts
  packages/kcms/src/team/service/entryCode.ts
Labels: 新機能, backend

#872 chore: SetMainMatchWinnerServiceを実装
  packages/kcms/src/match/adaptor/controller/match.ts
  packages/kcms/src/match/adaptor/validator/match.ts
  packages/kcms/src/match/main.ts
  packages/kcms/src/match/model/main.test.ts
  packages/kcms/src/match/model/main.ts
  packages/kcms/src/match/routing.ts
  packages/kcms/src/match/service/setMainWinner.test.ts
  packages/kcms/src/match/service/setMainWinner.ts
Labels: 新機能, backend

#886 fix: PrismaMainMatchRepositoryでchildIDが正しく設定できない問題の解決
  packages/kcms/src/match/adaptor/prisma/mainMatchRepository.ts
Labels: バグ/不具合, backend

#537 feat:試合終了後の結果詳細画面
  packages/kcmsf/src/components/MatchResult.tsx
  packages/kcmsf/src/components/WinnerSelector.tsx
  packages/kcmsf/src/components/match/MatchNameCard.tsx
  packages/kcmsf/src/components/match/MatchPointCard.tsx
  packages/kcmsf/src/hooks/useMatchInfo.ts
  packages/kcmsf/src/hooks/useMatchResult.ts
  packages/kcmsf/src/hooks/useTournamentData.ts
  packages/kcmsf/src/pages/match.tsx
  packages/kcmsf/src/types/api/match.ts
  packages/kcmsf/src/types/match.ts
Labels: frontend

#889 feat: 勝敗を自動決定するように
  packages/kcms/src/match/service/createRunResult.test.ts
  packages/kcms/src/match/service/createRunResult.ts
Labels: 新機能, backend
